language: android
dist: trusty
jdk: openjdk11
android:
  components:
    - build-tools-30.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'
before_install:
  - chmod +x gradlew
  - touch $HOME/.android/repositories.cfg
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip" -O commandlinetools.zip
  - unzip commandlinetools.zip -d ~/android-sdk/
  - yes | ~/android-sdk/cmdline-tools/bin/sdkmanager "platforms;android-23" --sdk_root=~/android-sdk
  - yes | ~/android-sdk/cmdline-tools/bin/sdkmanager "build-tools;30.0.2" --sdk_root=~/android-sdk
script:
  - ./gradlew check
