{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.kshoji",
    "module": "midi-driver",
    "version": "0.1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.kshoji",
          "module": "javax-sound-midi",
          "version": {
            "requires": "0.0.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javax-sound-midi",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "midi-driver-0.1.12.1.aar",
          "url": "midi-driver-0.1.12.1.aar",
          "size": 70911,
          "sha512": "ab0a417c721ff30dcd3c14f3d12593e8ccc5fe713fb5c3f62dfbe235820cf8c4df98062390571eb52e525188a0b3397e6438081a7fad19095c77d7d04bbb7a28",
          "sha256": "a708f189ae31dc5cb71d3b34a5658e818534a4bf898acd304c69b6a6df2a7acc",
          "sha1": "8941036c63c1eb2480ebe75c8b8bd394cd9564fa",
          "md5": "35a720832037feb74b9aa8cd630dcb3e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.kshoji",
          "module": "javax-sound-midi",
          "version": {
            "requires": "0.0.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javax-sound-midi",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "midi-driver-0.1.12.1.aar",
          "url": "midi-driver-0.1.12.1.aar",
          "size": 70911,
          "sha512": "ab0a417c721ff30dcd3c14f3d12593e8ccc5fe713fb5c3f62dfbe235820cf8c4df98062390571eb52e525188a0b3397e6438081a7fad19095c77d7d04bbb7a28",
          "sha256": "a708f189ae31dc5cb71d3b34a5658e818534a4bf898acd304c69b6a6df2a7acc",
          "sha1": "8941036c63c1eb2480ebe75c8b8bd394cd9564fa",
          "md5": "35a720832037feb74b9aa8cd630dcb3e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "midi-driver-0.1.12.1-sources.jar",
          "url": "midi-driver-0.1.12.1-sources.jar",
          "size": 42182,
          "sha512": "d1a1377c853ab82963668970eff1a9e3c9f3917be12e5a97064da0c21893d99c17dd0cf61473f49469435b8ba906318c6c114906978e0def7310818d9b84b6fc",
          "sha256": "ec9e166daa8527c5e6c9de928724996884ba446122fb3ab606da9eaea3c75663",
          "sha1": "974b386f0593afab2b8d9a20df037f0e6b2b7259",
          "md5": "1e9ff76312824b175aa355ad2f3cc59f"
        }
      ]
    }
  ]
}
